---
title: "project model 3 k-mean clustering"
author: "Jingjing Li"
date: "2022-12-16"
output:
  pdf_document:
    latex_engine: xelatex
  word_document: default
---

I cannot knit all 3 clustering models at once, so I did them separately.


Helper packages

```{r}
library(tidyverse)
library(dplyr)
library(stringr)     
library(gridExtra)   
library(cluster)     
library(factoextra) 
library(mclust)
```

process the data
```{r}
df <-read.csv("radiomics_completedata.csv")

df <- na.omit(df)

df<-select(df,-c(Institution, Failure.binary))

set.seed(123)
```

K-mean clustering
```{r}
#function to compute total within-cluster sum of square 
wss <- function(k) {
  kmeans(df, k, nstart = 10)$tot.withinss
}

# Compute and plot wss for k = 1 to k = 15
k.values <- 1:15

# extract wss for 2-15 clusters
wss_values <- map_dbl(k.values, wss)

#optimal number of cluster
fviz_nbclust(df, kmeans, method = "silhouette")

# compute gap statistic
set.seed(123)
gap_stat <- clusGap(df, FUN = kmeans, nstart = 25,
                    K.max = 10, B = 50)
# Print the result
print(gap_stat, method = "firstmax")

fviz_gap_stat(gap_stat)

# Compute k-means clustering with k = 2
set.seed(123)
final <- kmeans(df, 2, nstart = 25)
print(final)

#final data
fviz_cluster(final, data = df)
```